import {decodeCsv,classify,buildReport,fmtDelta,download} from './core.js';
const $=s=>document.querySelector(s);let files=[],report=null,settings={conversionEvents:['generate_lead','form_submit','問い合わせ'],sigma:2,months:6};
function toast(s){$('#toast').textContent=s;setTimeout(()=>$('#toast').textContent='',3500)}
async function addFiles(list){for(const file of list){if(!/\.csv$/i.test(file.name)){files.push({name:file.name,kind:'unknown',rows:[],header:[],month:null});continue}const text=decodeCsv(await file.arrayBuffer());files.push({name:file.name,...classify(file.name,text)})}render()}
function chipKind(k){return {'ga4-channel':'GA4チャネル','ga4-landing':'GA4 LP','gsc-query':'GSCクエリ','gsc-page':'GSCページ',unknown:'不明'}[k]||k}
function render(){report=buildReport(files,settings);$('#chips').innerHTML=files.map(f=>`<span class="chip ${f.kind==='unknown'?'bad':''}"><b>${chipKind(f.kind)}</b>${esc(f.name)}<i>${f.month||'月不明'} / ${f.rows.length}行</i></span>`).join('');$('#report').hidden=!report.current; if(report.current) $('#report').innerHTML=reportHtml(report,true);toast(`${files.length}ファイル読込 / 対象月 ${report.current||'未確定'}`)}
function reportHtml(r,interactive=false){return `<article class="monthly"><section class="hero"><p class="eyebrow">${r.current||''} 月報</p><h2>結論サマリー</h2><ol>${r.summary.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>${tableSection('流入層',channelRows(r),['チャネル','Sessions','前月比','Engaged','New users'])}${tableSection('LP層',lpRows(r),['LP','Sessions','Eng率','問い合わせ','歩留まり'])}${tableSection('SEO層',seoRows(r),['クエリ','Imp','Clicks','CTR','掲載順位','順位前年差'])}${tableSection('変化層（異常）',anomalyRows(r),['種別','要因','指標','値','z-score'])}<section><h2>データの注記</h2><ul>${r.files.map(f=>`<li>${esc(f.name)} — ${chipKind(f.kind)} / ${f.month||'月不明'} / ${f.rows.length}行</li>`).join('')}</ul></section></article>`}
function tableSection(title,rows,heads){return `<section><h2>${title}</h2><div class="table"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">データなし</td></tr>`}</tbody></table></div></section>`}
function channelRows(r){return r.channel.sort((a,b)=>b.sessions-a.sessions).map(x=>`<tr><td>${esc(x.dim)}</td><td>${num(x.sessions)}<div class="bar" style="--w:${Math.min(100,x.sessions/Math.max(...r.channel.map(c=>c.sessions),1)*100)}%"></div></td><td class="${x.sessions-(x.prev.sessions||0)>=0?'up':'down'}">${fmtDelta(x.sessions-(x.prev.sessions||0))}</td><td>${num(x.engaged)}</td><td>${num(x.newUsers)}</td></tr>`).join('')}
function lpRows(r){return r.lp.sort((a,b)=>b.sessions-a.sessions).slice(0,20).map(x=>`<tr><td>${esc(x.dim)}</td><td>${num(x.sessions)}</td><td>${pct(x.engRate)}</td><td>${num(x.conversions)}</td><td>${pct(x.rate)}</td></tr>`).join('')}
function seoRows(r){return r.seo.sort((a,b)=>b.impressions-a.impressions).slice(0,30).map(x=>{const d=(x.prev.position||0)-x.position;return `<tr><td>${esc(x.dim)}</td><td>${num(x.impressions)}</td><td>${num(x.clicks)}</td><td>${pct(x.ctr)}</td><td>${x.position?.toFixed?.(1)??''}</td><td class="${d>=0?'up':'down'}">${d?fmtDelta(Math.round(d*10)/10):'—'}</td></tr>`}).join('')}
function anomalyRows(r){return r.anomalies.map(a=>`<tr><td>${chipKind(a.kind)}</td><td>${esc(a.dim)}</td><td>${a.metric}</td><td>${num(a.value)}</td><td class="${a.z>=0?'up':'down'}">${a.z.toFixed(2)}</td></tr>`).join('')}
function markdown(r){return `# GA4 Bench 月報 ${r.current}\n\n## 結論サマリー\n${r.summary.map(x=>`- ${x}`).join('\n')}\n\n## 異常\n${r.anomalies.map(a=>`- ${chipKind(a.kind)} / ${a.dim} / ${a.metric}: ${a.value} (z=${a.z.toFixed(2)})`).join('\n')||'- なし'}\n`}
function standalone(){return `<!doctype html><meta charset="utf-8"><title>GA4 Bench 月報</title><style>${document.querySelector('style').textContent}</style>${reportHtml(report)}`}
function aiBundle(){return `${markdown(report)}\n\n## AIへの相談\n1. この月報の一番重要な変化を、経営向けに3行で解釈してください。\n2. SEOクエリとLPの組み合わせから、来月増やすべきコンテンツ案を5つ出してください。\n3. 異常検知に出た要因について、計測ミスと実態変化の切り分け観点をください。\n`}
function esc(s){return String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function num(n){return Number(n||0).toLocaleString()}function pct(n){return n==null?'—':`${(n>1?n:n*100).toFixed(1)}%`}
$('#open').onclick=()=>{const i=document.createElement('input');i.type='file';i.multiple=true;i.accept='.csv';i.onchange=()=>addFiles(i.files);i.click()};$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('drag')};$('#drop').ondragleave=()=>$('#drop').classList.remove('drag');$('#drop').ondrop=e=>{e.preventDefault();$('#drop').classList.remove('drag');addFiles(e.dataTransfer.files)};$('#htmlOut').onclick=()=>report&&download(`ga4-bench-${report.current}.html`,standalone(),'text/html');$('#mdOut').onclick=()=>report&&download(`ga4-bench-${report.current}.md`,markdown(report),'text/markdown');$('#aiOut').onclick=async()=>{if(!report)return;const t=aiBundle();try{await navigator.clipboard.writeText(t);toast('AI相談バンドルをコピーしました')}catch{download(`ga4-ai-bundle-${report.current}.md`,t,'text/markdown')}};$('#settingsBtn').onclick=()=>$('#settings').showModal();$('#closeSettings').onclick=()=>$('#settings').close();$('#settingsExport').onclick=()=>download('ga4-bench-settings.json',JSON.stringify(settings,null,2),'application/json');$('#settingsImport').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=async()=>{settings=JSON.parse(await i.files[0].text());$('#sigma').value=settings.sigma||2;$('#months').value=settings.months||6;render()};i.click()};$('#sigma').onchange=e=>{settings.sigma=Number(e.target.value);render()};$('#months').onchange=e=>{settings.months=Number(e.target.value);render()};$('#sample').onclick=()=>toast('npm run generate:ga4-sample で testdata/ga4-sample/ に生成できます');
