export function normText(v){if(v==null)return null;let s=String(v).replace(/[Ａ-Ｚａ-ｚ０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/　/g,' ').trim();return s===''||s==='-'||s==='ー'?null:s}
export function normNum(v){if(typeof v==='number')return Number.isFinite(v)?v:null;let s=normText(v);if(s==null)return null;const pct=/%$/.test(s);const neg=/^△/.test(s)||/^\(.+\)$/.test(s);s=s.replace(/[¥￥,()△\\%]/g,'');if(s===''||!/^[+-]?[0-9.]+$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?(neg?-Math.abs(n):n):null}
export function decodeCsv(buf){const utf8=new TextDecoder('utf-8',{fatal:false}).decode(buf);if(!utf8.includes('�'))return utf8;try{return new TextDecoder('shift_jis',{fatal:false}).decode(buf)}catch{return utf8}}
export function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows}
export function tableFromCsv(text){const lines=parseCsv(text);const meta=lines.filter(r=>(r[0]||'').trim().startsWith('#')).map(r=>r.join(','));const chunks=[];let cur=[];for(const r of lines){if((r[0]||'').trim().startsWith('#'))continue;if(r.every(c=>String(c).trim()==='')){if(cur.length){chunks.push(cur);cur=[]}}else cur.push(r)}if(cur.length)chunks.push(cur);let best=chunks.sort((a,b)=>scoreTable(b)-scoreTable(a))[0]||[];const header=(best[0]||[]).map(h=>normText(h)||'');const rows=best.slice(1).filter(r=>r.some(c=>normText(c)!=null)).map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]??null])));return {meta,header,rows}}
function scoreTable(t){return (t.length||0)*((t[0]||[]).length||0)}
const aliases={month:['月','Month','期間','Date'],channel:['セッションのデフォルトチャネルグループ','Session default channel group','Default channel group','チャネル'],landing:['ランディング ページ','Landing page','Landing page + query string','ランディングページ'],sessions:['セッション','Sessions'],engaged:['エンゲージのあったセッション数','Engaged sessions'],newUsers:['新規ユーザー','New users'],engRate:['エンゲージメント率','Engagement rate'],conversions:['コンバージョン','Conversions','Key events','キーイベント'],query:['クエリ','Query','検索キーワード'],page:['ページ','Top pages','Page'],clicks:['クリック数','Clicks'],impressions:['表示回数','Impressions'],ctr:['CTR'],position:['掲載順位','Position']};
function col(header,key){const low=header.map(h=>String(h).toLowerCase());for(const a of aliases[key]){const i=low.indexOf(a.toLowerCase());if(i>=0)return header[i]}return null}
export function inferMonth(name,meta=[],rows=[]){const s=[name,...meta].join(' ');let m=s.match(/(20\d{2})[\/-年]?(0?[1-9]|1[0-2])/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}`;const c=Object.keys(rows[0]||{}).find(k=>aliases.month.includes(k));if(c){const v=normText(rows[0][c]);m=v?.match(/(20\d{2})[\/-年]?(0?[1-9]|1[0-2])/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}`}return null}
export function classify(name,text){const t=tableFromCsv(text);const h=t.header;const has=k=>!!col(h,k);let kind='unknown';if(has('channel')&&has('sessions'))kind='ga4-channel';else if(has('landing')&&has('sessions'))kind='ga4-landing';else if(has('query')&&has('clicks')&&has('impressions'))kind='gsc-query';else if(has('page')&&has('clicks')&&has('impressions'))kind='gsc-page';return {kind,month:inferMonth(name,t.meta,t.rows),...t}}
export function normalizeRecord(file){const h=file.header;const c=k=>col(h,k);return file.rows.map(r=>{const g=k=>r[c(k)];return {month:file.month,kind:file.kind,dim:file.kind==='ga4-channel'?normText(g('channel')):file.kind==='ga4-landing'?normText(g('landing')):file.kind==='gsc-query'?normText(g('query')):normText(g('page')),sessions:normNum(g('sessions'))||0,engaged:normNum(g('engaged'))||0,newUsers:normNum(g('newUsers'))||0,engRate:normNum(g('engRate')),conversions:normNum(g('conversions'))||0,clicks:normNum(g('clicks'))||0,impressions:normNum(g('impressions'))||0,ctr:normNum(g('ctr')),position:normNum(g('position'))}})}
export function buildReport(files,settings={sigma:2,months:6}){const valid=files.filter(f=>f.kind!=='unknown'&&f.month);const by=new Map();for(const f of valid)by.set(`${f.kind}|${f.month}`,f);const rec=[...by.values()].flatMap(normalizeRecord);const months=[...new Set(rec.map(r=>r.month))].sort();const current=months.at(-1),prev=months.at(-2);const pick=(kind,m)=>rec.filter(r=>r.kind===kind&&r.month===m);const sum=(rs,k)=>rs.reduce((s,r)=>s+(r[k]||0),0);const channel=pick('ga4-channel',current).map(r=>({...r,prev:(pick('ga4-channel',prev).find(p=>p.dim===r.dim)||{})}));const lp=pick('ga4-landing',current).map(r=>({...r,rate:r.sessions?r.conversions/r.sessions:null}));const seo=pick('gsc-query',current).map(r=>({...r,prev:(pick('gsc-query',prev).find(p=>p.dim===r.dim)||{})}));const anomalies=[];for(const kind of ['ga4-channel','ga4-landing','gsc-query']){for(const dim of new Set(rec.filter(r=>r.kind===kind).map(r=>r.dim))){for(const metric of kind.startsWith('ga4')?['sessions','conversions']:['impressions','clicks','position']){const series=months.map(m=>(rec.find(r=>r.kind===kind&&r.dim===dim&&r.month===m)||{})[metric]||0);if(series.length<3)continue;const vals=series.slice(0,-1),avg=vals.reduce((a,b)=>a+b,0)/vals.length,sd=Math.sqrt(vals.reduce((a,b)=>a+(b-avg)**2,0)/vals.length)||1,z=(series.at(-1)-avg)/sd;if(Math.abs(z)>=Number(settings.sigma||2))anomalies.push({kind,dim,metric,value:series.at(-1),z})}}}
const sCur=sum(pick('ga4-channel',current),'sessions'),sPrev=sum(pick('ga4-channel',prev),'sessions');const deltas=channel.map(r=>({dim:r.dim,delta:r.sessions-(r.prev.sessions||0)})).sort((a,b)=>b.delta-a.delta);const summary=[`総セッションは ${sCur.toLocaleString()}（前月比 ${fmtDelta(sCur-sPrev)}）。`,deltas.length?`最伸長チャネルは ${deltas[0].dim}（${fmtDelta(deltas[0].delta)}）、最下落は ${deltas.at(-1).dim}（${fmtDelta(deltas.at(-1).delta)}）。`:'チャネル比較に必要な前月データが不足しています。',`異常検知は ${anomalies.length} 件（rolling z-score、閾値 ${settings.sigma||2}σ）。`];return {months,current,prev,files,summary,channel,lp,seo,anomalies,settings}}
export function fmtDelta(n){return `${n>=0?'▲':'▼'}${Math.abs(n).toLocaleString()}`}
export function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
