import perspective from '@finos/perspective';
import '@finos/perspective-viewer';
import '@finos/perspective-viewer-datagrid';
import * as XLSX from 'xlsx';
const $=s=>document.querySelector(s);let master=null,worker=null,rows=[];
const defaultMaster={meta:{name:'商材分類 v1',updated:'2026-07-04',note:''},target_column_candidates:['商品コード','商品CD','PRODUCT_CODE'],levels:['大分類','中分類','小分類'],rules:[{match:{type:'exact',value:'F001'},assign:['火災','企業財産','オールリスク']},{match:{type:'prefix',value:'F'},assign:['火災','企業財産','その他']},{match:{type:'regex',value:'^A[0-9]{3}$'},assign:['自動車','フリート','その他']},{match:{type:'range',min:1000,max:1999},assign:['新種','賠償','その他']}],unmatched:['未分類','未分類','未分類']};
function toast(m){$('#toast').textContent=m;setTimeout(()=>$('#toast').textContent='',3000)}
function normText(v){if(v==null)return null;let s=String(v).replace(/[Ａ-Ｚａ-ｚ０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/　/g,' ').trim();return s===''||s==='-'||s==='ー'?null:s}
function normNum(v){let s=normText(v);if(s==null)return null;let neg=/^△/.test(s)||/^\(.+\)$/.test(s);s=s.replace(/[¥￥,()△]/g,'');let n=Number(s);return Number.isFinite(n)?(neg?-Math.abs(n):n):null}
function infer(vals){let n=0,d=0,t=0;for(const v of vals){if(v==null)continue;t++;if(normNum(v)!=null)n++;if(!Number.isNaN(Date.parse(v)))d++}return n/t>.8?'number':d/t>.8?'date':'string'}
function normalize(raw){const cols=Object.keys(raw[0]||{});const types=Object.fromEntries(cols.map(c=>[c,infer(raw.slice(0,200).map(r=>r[c]))]));return raw.map(r=>Object.fromEntries(cols.map(c=>[c,types[c]==='number'?normNum(r[c]):normText(r[c])])))}
function applyMaster(data,m){const col=m.target_column_candidates.find(c=>c in (data[0]||{}));let unmatched=0;const hits=Array(m.rules.length).fill(0);const out=data.map(r=>{let a=m.unmatched,hit=-1,v=r[col];for(let i=0;i<m.rules.length;i++){const mt=m.rules[i].match;const s=normText(v);let ok=mt.type==='exact'?s===mt.value:mt.type==='prefix'?s?.startsWith(mt.value):mt.type==='regex'?new RegExp(mt.value).test(s||''):mt.type==='range'?(normNum(v)>=mt.min&&normNum(v)<=mt.max):false;if(ok){a=m.rules[i].assign;hit=i;hits[i]++;break}}if(hit<0)unmatched++;return {...r,[m.levels[0]]:a[0],[m.levels[1]]:a[1],[m.levels[2]]:a[2]}});$('#unmatched b').textContent=unmatched;$('#unmatched').classList.toggle('warn',unmatched>0);return {out,hits,unmatched,col}}
async function loadFile(file){toast(`読込中 0/${file.size} bytes`);let raw;if(file.name.endsWith('.csv')){raw=XLSX.utils.sheet_to_json(XLSX.read(await file.arrayBuffer(),{type:'array'}).Sheets.Sheet1,{defval:null})}else{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:null})}rows=normalize(raw);if(master)rows=applyMaster(rows,master).out;await render(rows,file.name);toast(`完了 ${rows.length}行`)}
async function render(data,name){$('#start').hidden=true;$('#bench').hidden=false;worker=worker||await perspective.worker();$('#panes').innerHTML='';for(let i=0;i<3;i++){const p=document.createElement('section');p.className='pane';p.innerHTML=`<h2>${i+1} ${name}</h2><perspective-viewer></perspective-viewer>`;$('#panes').append(p);const table=await worker.table(data);const v=p.querySelector('perspective-viewer');v.load(table);v.restore({plugin:'Datagrid',group_by:['大分類','中分類','小分類'].filter(c=>c in data[0]),columns:Object.keys(data[0]||{}).slice(0,12)});}}
$('#open').onclick=()=>$('#file').click();$('#file').onchange=e=>loadFile(e.target.files[0]);$('#masterOpen').onclick=()=>{master=defaultMaster;toast('標準マスタを読込');if(rows.length){rows=applyMaster(rows,master).out;render(rows,'再集計')}};$('#specBtn').onclick=()=>$('#spec').showModal();$('#closeSpec').onclick=()=>$('#spec').close();addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='o'){e.preventDefault();$('#file').click()}if(e.key==='Escape')$('#spec').close()});
